export const BARRIOS_MONTEVIDEO: string[] = [
  'Aguada', 'Aire Puro', 'Atahualpa', 'Bañados de Carrasco',
  'Barrio Sur', 'Belvedere', 'Brazo Oriental', 'Buceo',
  'Capurro', 'Carrasco', 'Carrasco Norte', 'Casabó',
  'Casavalle', 'Castro', 'Centro', 'Cerrito',
  'Cerro', 'Ciudad Vieja', 'Colón Centro', 'Colón Noroeste',
  'Conciliación', 'Cordón', 'Flor de Maroñas', 'Goes',
  'Ituzaingó', 'Jacinto Vera', 'La Blanqueada', 'La Comercial',
  'La Figurita', 'La Teja', 'La Unión', 'Larrañaga',
  'Las Acacias', 'Las Canteras', 'Lezica', 'Madureira',
  'Malvín', 'Malvín Norte', 'Manga', 'Maroñas',
  'Mercado Modelo', 'Millán', 'Montevideo Rural',
  'Nuevo París', 'Palermo', 'Parque Batlle', 'Parque Rodó',
  'Paso de la Arena', 'Paso de las Duranas', 'Peñarol',
  'Piedras Blancas', 'Pocitos', 'Prado', 'Punta Carretas',
  'Punta Gorda', 'Reducto', 'Rincón de Millán', 'Sayago',
  'Talar de Punta Gorda', 'Toledo Chico', 'Tres Cruces',
  'Tres Ombúes', 'Unión', 'Villa Española', 'Villa García',
  'Villa Muñoz', 'Villa del Cerro',
]
